import dash
import networkx as nx
from dash import dcc, html
import dash_bootstrap_components as dbc

from visualization import nx_to_cytoscape, handle_node_properties, create_dash_layout, app

# Code to create the basic fdfg
from fhy.ir import Identifier
from fhy.fdfg.core import FDFG, SourceNode, SinkNode
from fhy.fdfg.node.fractalized import FractalizedNode, FunctionNode
from fhy.fdfg.node.parametric import LoopNode, ReductionNode
from fhy.fdfg.edge import Edge
from fhy.fdfg.node.primitive import PrimitiveNode
import fhy.fdfg.ops as fdfg_op
from fhy.fdfg.builtins.reductions import BUILTIN_REDUCTION_FUNCTION_IDENTIFIERS, _BUILTIN_REDUCTION_FUNCTION_OPS


# Example 1
# fdfg = FDFG()
# a = Identifier("a")
# b = Identifier("b")
# c = Identifier("c")
# d = Identifier("d")
# e = Identifier("e")
# op_1_node_name = Identifier("op1")
# op_2_node_name = Identifier("op2")
# op_1_node = PrimitiveNode(fdfg_op.add_op)
# op_2_node = PrimitiveNode(fdfg_op.div_op)
# fdfg.add_node(op_1_node_name, op_1_node)
# fdfg.add_node(op_2_node_name, op_2_node)
# fdfg.add_edge(fdfg.source_node_name, op_1_node_name, a, 0, 0)
# fdfg.add_edge(fdfg.source_node_name, op_1_node_name, b, 1, 1)
# fdfg.add_edge(op_1_node_name, op_2_node_name, c, 0, 0)
# fdfg.add_edge(fdfg.source_node_name, op_2_node_name, d, 2, 1)
# fdfg.add_edge(op_2_node_name, fdfg.sink_node_name, e, 0, 0)




# Example 2
# function_fdfg = FDFG()
# a = Identifier("a")
# b = Identifier("b")
# c = Identifier("c")
# op_node_name = Identifier("op")
# op_node = PrimitiveNode(fdfg_op.add_op)
# function_fdfg.add_node(op_node_name, op_node)
# function_fdfg.add_edge(function_fdfg.source_node_name, op_node_name, a, 0, 0)
# function_fdfg.add_edge(function_fdfg.source_node_name, op_node_name, b, 1, 1)
# function_fdfg.add_edge(op_node_name, function_fdfg.sink_node_name, c, 0, 0)
# fdfg = FDFG()
# x = Identifier("x")
# y = Identifier("y")
# z = Identifier("z")
# function_node_name = Identifier("function_node")
# function_name = Identifier("function")
# function_node = FunctionNode(function_name, fdfg=function_fdfg)
# fdfg.add_node(function_node_name, function_node)
# fdfg.add_edge(fdfg.source_node_name, function_node_name, x, 0, 0)
# fdfg.add_edge(fdfg.source_node_name, function_node_name, y, 1, 1)
# fdfg.add_edge(function_node_name, fdfg.sink_node_name, z, 0, 0)






# Example 3
# foo_fdfg = FDFG()
# a = Identifier("a")
# b = Identifier("b")
# c = Identifier("c")
# d = Identifier("d")
# op_add1 = Identifier("op_add1")
# op_add2 = Identifier("op_add2")

# op_add1_node = PrimitiveNode(fdfg_op.add_op)
# op_add2_node = PrimitiveNode(fdfg_op.add_op)

# foo_fdfg.add_node(op_add1, op_add1_node)
# foo_fdfg.add_node(op_add2, op_add2_node)

# foo_fdfg.add_edge(foo_fdfg.source_node_name, op_add1, a, 0, 0)
# foo_fdfg.add_edge(foo_fdfg.source_node_name, op_add1, b, 1, 1)
# foo_fdfg.add_edge(op_add1, op_add2, d, 0, 0)
# foo_fdfg.add_edge(foo_fdfg.source_node_name, op_add2, b, 1, 1)
# foo_fdfg.add_edge(op_add2, foo_fdfg.sink_node_name, c, 0, 0)

# bar_fdfg = FDFG()
# i = Identifier("i")
# j = Identifier("j")
# k = Identifier("k")

# foo_node_name = Identifier("foo_node")
# foo_name = Identifier("foo")

# foo_node = FunctionNode(foo_name, fdfg=foo_fdfg)
# op_add = Identifier("op_add")
# op_add_node = PrimitiveNode(fdfg_op.add_op)

# bar_fdfg.add_node(foo_node_name, foo_node)
# bar_fdfg.add_node(op_add, op_add_node)

# bar_fdfg.add_edge(bar_fdfg.source_node_name, foo_node_name, i, 0, 0)
# bar_fdfg.add_edge(bar_fdfg.source_node_name, foo_node_name, i, 1, 1)
# bar_fdfg.add_edge(bar_fdfg.source_node_name, foo_node_name, j, 2, 2)
# bar_fdfg.add_edge(bar_fdfg.source_node_name, op_add, i, 0, 0)
# bar_fdfg.add_edge(foo_node_name, op_add, k, 0, 1)
# bar_fdfg.add_edge(op_add, bar_fdfg.sink_node_name, k, 0, 0)

# main_fdfg = FDFG()
# x = Identifier("x")
# y = Identifier("y")
# z = Identifier("z")
# zz = Identifier("zz")

# op_mul = Identifier("op_mul")
# op_mul_node = PrimitiveNode(fdfg_op.mul_op)

# bar_node_name = Identifier("bar_node")
# bar_name = Identifier("bar")

# bar_node = FunctionNode(bar_name, fdfg=bar_fdfg)

# main_fdfg.add_node(op_mul, op_mul_node)
# main_fdfg.add_node(bar_node_name, bar_node)

# main_fdfg.add_edge(main_fdfg.source_node_name, op_mul, x, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, op_mul, y, 1, 1)
# main_fdfg.add_edge(op_mul, bar_node_name, z, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, bar_node_name, y, 1, 1)
# main_fdfg.add_edge(bar_node_name, main_fdfg.sink_node_name, zz, 0, 0)

# fdfg = main_fdfg






# Example 4 (generated by chatgpt, might have errors)
# foo_fdfg = FDFG()
# x = Identifier("x")
# y = Identifier("y")
# z = Identifier("z")
# i = Identifier("i")

# loop_fdfg = FDFG()
# _x = Identifier("_x")
# _y = Identifier("_y")
# _z = Identifier("_z")
# loop_op_node_name = Identifier("loop_op")
# loop_op_node = PrimitiveNode(fdfg_op.add_op)

# loop_fdfg.add_node(loop_op_node_name, loop_op_node)
# loop_fdfg.add_edge(loop_fdfg.source_node_name, loop_op_node_name, _x, 0, 0)
# loop_fdfg.add_edge(loop_fdfg.source_node_name, loop_op_node_name, _y, 1, 1)
# loop_fdfg.add_edge(loop_op_node_name, loop_fdfg.sink_node_name, _z, 0, 0)

# loop_node_name = Identifier("loop")
# loop_node = LoopNode({i}, fdfg=loop_fdfg)

# foo_fdfg.add_node(loop_node_name, loop_node)
# foo_fdfg.add_edge(foo_fdfg.source_node_name, loop_node_name, x, 0, 0)
# foo_fdfg.add_edge(foo_fdfg.source_node_name, loop_node_name, y, 1, 1)
# foo_fdfg.add_edge(loop_node_name, foo_fdfg.sink_node_name, z, 0, 0)

# main_fdfg = FDFG()
# a = Identifier("a")
# b = Identifier("b")
# c = Identifier("c")
# i = Identifier("i")

# foo_node_name = Identifier("foo_node")
# foo_name = Identifier("foo")

# foo_node = FunctionNode(foo_name, fdfg=foo_fdfg)

# loop_fdfg = FDFG()
# _a = Identifier("_a")
# _b = Identifier("_b")
# _c = Identifier("_c")
# loop_op_node_name = Identifier("loop_op")
# loop_op_node = PrimitiveNode(fdfg_op.add_op)

# loop_fdfg.add_node(loop_op_node_name, loop_op_node)
# loop_fdfg.add_edge(loop_fdfg.source_node_name, loop_op_node_name, _a, 0, 0)
# loop_fdfg.add_edge(loop_fdfg.source_node_name, loop_op_node_name, _b, 1, 1)
# loop_fdfg.add_edge(loop_op_node_name, loop_fdfg.sink_node_name, _c, 0, 0)

# loop_node_name = Identifier("loop")
# loop_node = LoopNode({i}, fdfg=loop_fdfg)

# main_fdfg.add_node(foo_node_name, foo_node)
# main_fdfg.add_node(loop_node_name, loop_node)

# main_fdfg.add_edge(main_fdfg.source_node_name, foo_node_name, a, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, foo_node_name, b, 1, 1)
# main_fdfg.add_edge(foo_node_name, loop_node_name, c, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, loop_node_name, a, 1, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, loop_node_name, b, 2, 1)
# main_fdfg.add_edge(loop_node_name, main_fdfg.sink_node_name, c, 0, 0)

# fdfg = main_fdfg





# # Example 5: matrix-vector multiplication (generated by chatgpt, might have errors)
# # Inner loop FDFG for the reduction operation
# inner_loop_fdfg = FDFG()
# __A = Identifier("__A")
# __x = Identifier("__x")
# __out = Identifier("__out")
# inner_loop_op_node_name = Identifier("inner_loop_op")
# inner_loop_op_node = PrimitiveNode(fdfg_op.mul_op)
# inner_loop_fdfg.add_node(inner_loop_op_node_name, inner_loop_op_node)
# inner_loop_fdfg.add_edge(inner_loop_fdfg.source_node_name, inner_loop_op_node_name, __A, 0, 0)
# inner_loop_fdfg.add_edge(inner_loop_fdfg.source_node_name, inner_loop_op_node_name, __x, 1, 1)
# inner_loop_fdfg.add_edge(inner_loop_op_node_name, inner_loop_fdfg.sink_node_name, __out, 0, 0)

# # Outer loop FDFG for the whole function
# outer_fdfg = FDFG()
# _A = Identifier("_A")
# _x = Identifier("_x")
# _y = Identifier("_y")
# i = Identifier("i")
# j = Identifier("j")
# outer_loop_node_name = Identifier("outer_loop")
# outer_loop_node = LoopNode({i, j}, fdfg=inner_loop_fdfg)
# outer_fdfg.add_node(outer_loop_node_name, outer_loop_node)
# outer_fdfg.add_edge(outer_fdfg.source_node_name, outer_loop_node_name, _A, 0, 0)
# outer_fdfg.add_edge(outer_fdfg.source_node_name, outer_loop_node_name, _x, 1, 1)
# outer_fdfg.add_edge(outer_loop_node_name, outer_fdfg.sink_node_name, _y, 0, 0)

# # Main function FDFG for matvec_mul
# main_fdfg = FDFG()
# A = Identifier("A")
# x = Identifier("x")
# y = Identifier("y")
# matvec_node_name = Identifier("matvec_node")

# matvec_node = ReductionNode(BUILTIN_REDUCTION_FUNCTION_IDENTIFIERS["sum"], {i}, fdfg=outer_fdfg)
# main_fdfg.add_node(matvec_node_name, matvec_node)
# main_fdfg.add_edge(main_fdfg.source_node_name, matvec_node_name, A, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, matvec_node_name, x, 1, 1)
# main_fdfg.add_edge(matvec_node_name, main_fdfg.sink_node_name, y, 0, 0)

# fdfg = main_fdfg





# # needs fixing
# # Example 5
# # Define the main FDFG
# main_fdfg = FDFG()

# # Define identifiers
# a = Identifier("a")
# b = Identifier("b")
# c = Identifier("c")
# d = Identifier("d")
# e = Identifier("e")
# f = Identifier("f")
# g = Identifier("g")
# h = Identifier("h")
# i = Identifier("i")
# j = Identifier("j")

# # Define multiple sub-FDFGs
# sub_fdfg1 = FDFG()
# sub_fdfg2 = FDFG()
# sub_fdfg3 = FDFG()

# # Define identifiers for sub-FDFGs
# x1 = Identifier("x1")
# y1 = Identifier("y1")
# z1 = Identifier("z1")
# x2 = Identifier("x2")
# y2 = Identifier("y2")
# z2 = Identifier("z2")
# x3 = Identifier("x3")
# y3 = Identifier("y3")
# z3 = Identifier("z3")

# # Define nodes for sub-FDFGs
# op1_node_name = Identifier("op1")
# op1_node = PrimitiveNode(fdfg_op.add_op)
# op2_node_name = Identifier("op2")
# op2_node = PrimitiveNode(fdfg_op.sub_op)
# op3_node_name = Identifier("op3")
# op3_node = PrimitiveNode(fdfg_op.mul_op)

# sub_fdfg1.add_node(op1_node_name, op1_node)
# sub_fdfg1.add_edge(sub_fdfg1.source_node_name, op1_node_name, x1, 0, 0)
# sub_fdfg1.add_edge(sub_fdfg1.source_node_name, op1_node_name, y1, 1, 1)
# sub_fdfg1.add_edge(op1_node_name, sub_fdfg1.sink_node_name, z1, 0, 0)

# sub_fdfg2.add_node(op2_node_name, op2_node)
# sub_fdfg2.add_edge(sub_fdfg2.source_node_name, op2_node_name, x2, 0, 0)
# sub_fdfg2.add_edge(sub_fdfg2.source_node_name, op2_node_name, y2, 1, 1)
# sub_fdfg2.add_edge(op2_node_name, sub_fdfg2.sink_node_name, z2, 0, 0)

# sub_fdfg3.add_node(op3_node_name, op3_node)
# sub_fdfg3.add_edge(sub_fdfg3.source_node_name, op3_node_name, x3, 0, 0)
# sub_fdfg3.add_edge(sub_fdfg3.source_node_name, op3_node_name, y3, 1, 1)
# sub_fdfg3.add_edge(op3_node_name, sub_fdfg3.sink_node_name, z3, 0, 0)

# # Define FunctionNodes for sub-FDFGs
# function1_node_name = Identifier("function1_node")
# function1_node = FunctionNode(Identifier("function1"), fdfg=sub_fdfg1)

# function2_node_name = Identifier("function2_node")
# function2_node = FunctionNode(Identifier("function2"), fdfg=sub_fdfg2)

# function3_node_name = Identifier("function3_node")
# function3_node = FunctionNode(Identifier("function3"), fdfg=sub_fdfg3)

# # Add nodes and edges to main FDFG
# main_fdfg.add_node(function1_node_name, function1_node)
# main_fdfg.add_node(function2_node_name, function2_node)
# main_fdfg.add_node(function3_node_name, function3_node)

# main_fdfg.add_edge(main_fdfg.source_node_name, function1_node_name, a, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, function1_node_name, b, 1, 1)
# main_fdfg.add_edge(function1_node_name, function2_node_name, c, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, function2_node_name, d, 1, 1)
# main_fdfg.add_edge(function2_node_name, function3_node_name, e, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, function3_node_name, f, 1, 1)
# main_fdfg.add_edge(function3_node_name, main_fdfg.sink_node_name, g, 0, 0)

# # Add more edges to make it dense
# main_fdfg.add_edge(function1_node_name, function3_node_name, h, 2, 2)
# main_fdfg.add_edge(function2_node_name, main_fdfg.sink_node_name, i, 2, 2)
# main_fdfg.add_edge(main_fdfg.source_node_name, function1_node_name, j, 3, 3)
# main_fdfg.add_edge(function3_node_name, function1_node_name, a, 3, 3)
# main_fdfg.add_edge(function3_node_name, function2_node_name, b, 4, 4)

# fdfg = main_fdfg



# ResNet Example (generated by chatgpt, has semantic errors)
# Inner loop FDFG for the 2D convolution operation
conv_inner_loop_fdfg = FDFG()
__x = Identifier("__x")
__k = Identifier("__k")
__out = Identifier("__out")
conv_inner_loop_op_node_name = Identifier("conv_inner_loop_op")
conv_inner_loop_op_node = PrimitiveNode(fdfg_op.mul_op)  # Multiplication operation
conv_inner_loop_fdfg.add_node(conv_inner_loop_op_node_name, conv_inner_loop_op_node)
conv_inner_loop_fdfg.add_edge(conv_inner_loop_fdfg.source_node_name, conv_inner_loop_op_node_name, __x, 0, 0)
conv_inner_loop_fdfg.add_edge(conv_inner_loop_fdfg.source_node_name, conv_inner_loop_op_node_name, __k, 1, 1)
conv_inner_loop_fdfg.add_edge(conv_inner_loop_op_node_name, conv_inner_loop_fdfg.sink_node_name, __out, 0, 0)

# Outer loop FDFG for the convolution operation
conv_outer_fdfg = FDFG()
_x = Identifier("_x")
_k = Identifier("_k")
_y = Identifier("_y")
n = Identifier("n")
c = Identifier("c")
h = Identifier("h")
w = Identifier("w")
i = Identifier("i")
j = Identifier("j")
conv_outer_loop_node_name = Identifier("conv_outer_loop")
conv_outer_loop_node = LoopNode({n, c, h, w, i, j}, fdfg=conv_inner_loop_fdfg)
conv_outer_fdfg.add_node(conv_outer_loop_node_name, conv_outer_loop_node)
conv_outer_fdfg.add_edge(conv_outer_fdfg.source_node_name, conv_outer_loop_node_name, _x, 0, 0)
conv_outer_fdfg.add_edge(conv_outer_fdfg.source_node_name, conv_outer_loop_node_name, _k, 1, 1)
conv_outer_fdfg.add_edge(conv_outer_loop_node_name, conv_outer_fdfg.sink_node_name, _y, 0, 0)

# ReLU FDFG
relu_fdfg = FDFG()
relu_inner_loop_op_node_name = Identifier("relu_inner_loop_op")
relu_inner_loop_op_node = PrimitiveNode(fdfg_op.id_op)  # not max
relu_inner_loop_fdfg = FDFG()
relu_inner_loop_fdfg.add_node(relu_inner_loop_op_node_name, relu_inner_loop_op_node)
relu_inner_loop_fdfg.add_edge(relu_inner_loop_fdfg.source_node_name, relu_inner_loop_op_node_name, __x, 0, 0)
relu_inner_loop_fdfg.add_edge(relu_inner_loop_op_node_name, relu_inner_loop_fdfg.sink_node_name, __out, 0, 0)

relu_outer_fdfg = FDFG()
_relu_x = Identifier("_relu_x")
_relu_y = Identifier("_relu_y")
relu_outer_loop_node_name = Identifier("relu_outer_loop")
relu_outer_loop_node = ReductionNode(BUILTIN_REDUCTION_FUNCTION_IDENTIFIERS["max"], {n, c, h, w}, fdfg=relu_inner_loop_fdfg)
relu_outer_fdfg.add_node(relu_outer_loop_node_name, relu_outer_loop_node)
relu_outer_fdfg.add_edge(relu_outer_fdfg.source_node_name, relu_outer_loop_node_name, _relu_x, 0, 0)
relu_outer_fdfg.add_edge(relu_outer_loop_node_name, relu_outer_fdfg.sink_node_name, _relu_y, 0, 0)

# Main function FDFG for resnet_block
main_fdfg = FDFG()
x = Identifier("x")
k1 = Identifier("k1")
k2 = Identifier("k2")
conv1 = Identifier("conv1")
relu1 = Identifier("relu1")
conv2 = Identifier("conv2")
y = Identifier("y")
resnet_node_name = Identifier("resnet_node")

# First convolution
conv1_node_name = Identifier("conv1_node")
conv1_node = ReductionNode(BUILTIN_REDUCTION_FUNCTION_IDENTIFIERS["sum"], {n, c, h, w, i, j}, fdfg=conv_outer_fdfg)
main_fdfg.add_node(conv1_node_name, conv1_node)
main_fdfg.add_edge(main_fdfg.source_node_name, conv1_node_name, x, 0, 0)
main_fdfg.add_edge(main_fdfg.source_node_name, conv1_node_name, k1, 1, 1)

# ReLU
relu_node_name = Identifier("relu_node")
relu_node = FunctionNode(Identifier("relu"), fdfg=relu_outer_fdfg)
main_fdfg.add_node(relu_node_name, relu_node)
main_fdfg.add_edge(conv1_node_name, relu_node_name, conv1, 0, 0)

# Second convolution
conv2_node_name = Identifier("conv2_node")
conv2_node = ReductionNode(BUILTIN_REDUCTION_FUNCTION_IDENTIFIERS["sum"], {n, c, h, w, i, j}, fdfg=conv_outer_fdfg)
main_fdfg.add_node(conv2_node_name, conv2_node)
main_fdfg.add_edge(main_fdfg.source_node_name, conv2_node_name, x, 0, 0)
main_fdfg.add_edge(main_fdfg.source_node_name, conv2_node_name, k2, 2, 1)

# Skip connection and final addition
addition_fdfg = FDFG()
addition_inner_loop_op_node_name = Identifier("addition_inner_loop_op")
addition_inner_loop_op_node = PrimitiveNode(fdfg_op.add_op)  # Addition operation
addition_inner_loop_fdfg = FDFG()
addition_inner_loop_fdfg.add_node(addition_inner_loop_op_node_name, addition_inner_loop_op_node)
addition_inner_loop_fdfg.add_edge(addition_inner_loop_fdfg.source_node_name, addition_inner_loop_op_node_name, __x, 0, 0)
addition_inner_loop_fdfg.add_edge(addition_inner_loop_op_node_name, addition_inner_loop_fdfg.sink_node_name, _y, 1, 1)
addition_inner_loop_fdfg.add_edge(addition_inner_loop_op_node_name, addition_inner_loop_fdfg.sink_node_name, __out, 0, 0)

resnet_node = LoopNode({n, c, h, w}, fdfg=addition_inner_loop_fdfg)
main_fdfg.add_node(resnet_node_name, resnet_node)
main_fdfg.add_edge(relu_node_name, resnet_node_name, relu1, 0, 0)
main_fdfg.add_edge(conv2_node_name, resnet_node_name, conv2, 0, 1)
main_fdfg.add_edge(resnet_node_name, main_fdfg.sink_node_name, y, 0, 0)

fdfg = main_fdfg





# # Example 6
# # Define the main FDFG
# main_fdfg = FDFG()

# # Define identifiers for the main graph
# a = Identifier("a")
# b = Identifier("b")
# c = Identifier("c")
# d = Identifier("d")
# e = Identifier("e")
# f = Identifier("f")
# g = Identifier("g")
# h = Identifier("h")
# i = Identifier("i")
# j = Identifier("j")
# k = Identifier("k")
# l = Identifier("l")

# # Define multiple sub-FDFGs
# sub_fdfg1 = FDFG()
# sub_fdfg2 = FDFG()
# sub_fdfg3 = FDFG()
# sub_fdfg4 = FDFG()

# # Define identifiers for sub-FDFGs
# x1 = Identifier("x1")
# y1 = Identifier("y1")
# z1 = Identifier("z1")
# x2 = Identifier("x2")
# y2 = Identifier("y2")
# z2 = Identifier("z2")
# x3 = Identifier("x3")
# y3 = Identifier("y3")
# z3 = Identifier("z3")
# x4 = Identifier("x4")
# y4 = Identifier("y4")
# z4 = Identifier("z4")

# # Define nodes for sub-FDFGs
# op1_node_name = Identifier("op1")
# op1_node = PrimitiveNode(fdfg_op.add_op)
# op2_node_name = Identifier("op2")
# op2_node = PrimitiveNode(fdfg_op.sub_op)
# op3_node_name = Identifier("op3")
# op3_node = PrimitiveNode(fdfg_op.mul_op)
# op4_node_name = Identifier("op4")
# op4_node = PrimitiveNode(fdfg_op.div_op)

# # Sub FDFG 1
# sub_fdfg1.add_node(op1_node_name, op1_node)
# sub_fdfg1.add_edge(sub_fdfg1.source_node_name, op1_node_name, x1, 0, 0)
# sub_fdfg1.add_edge(sub_fdfg1.source_node_name, op1_node_name, y1, 1, 1)
# sub_fdfg1.add_edge(op1_node_name, sub_fdfg1.sink_node_name, z1, 0, 0)

# # Sub FDFG 2
# sub_fdfg2.add_node(op2_node_name, op2_node)
# sub_fdfg2.add_edge(sub_fdfg2.source_node_name, op2_node_name, x2, 0, 0)
# sub_fdfg2.add_edge(sub_fdfg2.source_node_name, op2_node_name, y2, 1, 1)
# sub_fdfg2.add_edge(op2_node_name, sub_fdfg2.sink_node_name, z2, 0, 0)

# # Sub FDFG 3
# sub_fdfg3.add_node(op3_node_name, op3_node)
# sub_fdfg3.add_edge(sub_fdfg3.source_node_name, op3_node_name, x3, 0, 0)
# sub_fdfg3.add_edge(sub_fdfg3.source_node_name, op3_node_name, y3, 1, 1)
# sub_fdfg3.add_edge(op3_node_name, sub_fdfg3.sink_node_name, z3, 0, 0)

# # Sub FDFG 4
# sub_fdfg4.add_node(op4_node_name, op4_node)
# sub_fdfg4.add_edge(sub_fdfg4.source_node_name, op4_node_name, x4, 0, 0)
# sub_fdfg4.add_edge(sub_fdfg4.source_node_name, op4_node_name, y4, 1, 1)
# sub_fdfg4.add_edge(op4_node_name, sub_fdfg4.sink_node_name, z4, 0, 0)

# # Define FunctionNodes for sub-FDFGs
# function1_node_name = Identifier("function1_node")
# function1_node = FunctionNode(Identifier("function1"), fdfg=sub_fdfg1)

# function2_node_name = Identifier("function2_node")
# function2_node = FunctionNode(Identifier("function2"), fdfg=sub_fdfg2)

# function3_node_name = Identifier("function3_node")
# function3_node = FunctionNode(Identifier("function3"), fdfg=sub_fdfg3)

# function4_node_name = Identifier("function4_node")
# function4_node = FunctionNode(Identifier("function4"), fdfg=sub_fdfg4)

# # Add nodes and edges to main FDFG
# main_fdfg.add_node(function1_node_name, function1_node)
# main_fdfg.add_node(function2_node_name, function2_node)
# main_fdfg.add_node(function3_node_name, function3_node)
# main_fdfg.add_node(function4_node_name, function4_node)

# # Add more connections to make it dense
# main_fdfg.add_edge(main_fdfg.source_node_name, function1_node_name, a, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, function1_node_name, b, 1, 1)
# main_fdfg.add_edge(function1_node_name, function2_node_name, c, 0, 0)
# main_fdfg.add_edge(function1_node_name, function3_node_name, d, 1, 1)
# main_fdfg.add_edge(function1_node_name, function4_node_name, e, 2, 2)
# main_fdfg.add_edge(function2_node_name, function3_node_name, f, 0, 0)
# main_fdfg.add_edge(function2_node_name, function4_node_name, g, 1, 1)
# main_fdfg.add_edge(function3_node_name, function4_node_name, h, 2, 2)
# main_fdfg.add_edge(function4_node_name, main_fdfg.sink_node_name, i, 0, 0)
# main_fdfg.add_edge(function3_node_name, main_fdfg.sink_node_name, j, 1, 1)
# main_fdfg.add_edge(function2_node_name, main_fdfg.sink_node_name, k, 2, 2)
# main_fdfg.add_edge(function1_node_name, main_fdfg.sink_node_name, l, 3, 3)

# # Add loops and more connections to increase density
# loop_fdfg = FDFG()
# _x = Identifier("_x")
# _y = Identifier("_y")
# _z = Identifier("_z")
# loop_op_node_name = Identifier("loop_op")
# loop_op_node = PrimitiveNode(fdfg_op.add_op)

# loop_fdfg.add_node(loop_op_node_name, loop_op_node)
# loop_fdfg.add_edge(loop_fdfg.source_node_name, loop_op_node_name, _x, 0, 0)
# loop_fdfg.add_edge(loop_fdfg.source_node_name, loop_op_node_name, _y, 1, 1)
# loop_fdfg.add_edge(loop_op_node_name, loop_fdfg.sink_node_name, _z, 0, 0)

# loop_node_name = Identifier("loop")
# loop_node = LoopNode({i}, fdfg=loop_fdfg)

# main_fdfg.add_node(loop_node_name, loop_node)
# main_fdfg.add_edge(main_fdfg.source_node_name, loop_node_name, a, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, loop_node_name, b, 1, 1)
# main_fdfg.add_edge(loop_node_name, function1_node_name, c, 0, 0)
# main_fdfg.add_edge(loop_node_name, function2_node_name, d, 1, 1)
# main_fdfg.add_edge(loop_node_name, function3_node_name, e, 2, 2)
# main_fdfg.add_edge(loop_node_name, function4_node_name, f, 3, 3)

# # Add nested loops
# nested_loop_fdfg = FDFG()
# _nested_x = Identifier("_nested_x")
# _nested_y = Identifier("_nested_y")
# _nested_z = Identifier("_nested_z")
# nested_loop_op_node_name = Identifier("nested_loop_op")
# nested_loop_op_node = PrimitiveNode(fdfg_op.mul_op)

# nested_loop_fdfg.add_node(nested_loop_op_node_name, nested_loop_op_node)
# nested_loop_fdfg.add_edge(nested_loop_fdfg.source_node_name, nested_loop_op_node_name, _nested_x, 0, 0)
# nested_loop_fdfg.add_edge(nested_loop_fdfg.source_node_name, nested_loop_op_node_name, _nested_y, 1, 1)
# nested_loop_fdfg.add_edge(nested_loop_op_node_name, nested_loop_fdfg.sink_node_name, _nested_z, 0, 0)

# nested_loop_node_name = Identifier("nested_loop")
# nested_loop_node = LoopNode({j}, fdfg=nested_loop_fdfg)

# main_fdfg.add_node(nested_loop_node_name, nested_loop_node)
# main_fdfg.add_edge(main_fdfg.source_node_name, nested_loop_node_name, g, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, nested_loop_node_name, h, 1, 1)
# main_fdfg.add_edge(nested_loop_node_name, loop_node_name, i, 0, 0)
# main_fdfg.add_edge(nested_loop_node_name, function1_node_name, j, 1, 1)
# main_fdfg.add_edge(nested_loop_node_name, function2_node_name, k, 2, 2)
# main_fdfg.add_edge(nested_loop_node_name, function3_node_name, l, 3, 3)

# fdfg = main_fdfg





# Example 7
# # Define the main FDFG
# main_fdfg = FDFG()

# # Define identifiers for the main graph
# a = Identifier("a")
# b = Identifier("b")
# c = Identifier("c")
# d = Identifier("d")
# e = Identifier("e")
# f = Identifier("f")
# g = Identifier("g")
# h = Identifier("h")
# i = Identifier("i")
# j = Identifier("j")
# k = Identifier("k")
# l = Identifier("l")

# # Define multiple sub-FDFGs
# sub_fdfg1 = FDFG()
# sub_fdfg2 = FDFG()
# sub_fdfg3 = FDFG()
# sub_fdfg4 = FDFG()

# # Define identifiers for sub-FDFGs
# x1 = Identifier("x1")
# y1 = Identifier("y1")
# z1 = Identifier("z1")
# x2 = Identifier("x2")
# y2 = Identifier("y2")
# z2 = Identifier("z2")
# x3 = Identifier("x3")
# y3 = Identifier("y3")
# z3 = Identifier("z3")
# x4 = Identifier("x4")
# y4 = Identifier("y4")
# z4 = Identifier("z4")

# # Define nodes for sub-FDFGs
# op1_node_name = Identifier("op1")
# op1_node = PrimitiveNode(fdfg_op.add_op)
# op2_node_name = Identifier("op2")
# op2_node = PrimitiveNode(fdfg_op.sub_op)
# op3_node_name = Identifier("op3")
# op3_node = PrimitiveNode(fdfg_op.mul_op)
# op4_node_name = Identifier("op4")
# op4_node = PrimitiveNode(fdfg_op.div_op)

# # Sub FDFG 1
# sub_fdfg1.add_node(op1_node_name, op1_node)
# sub_fdfg1.add_edge(sub_fdfg1.source_node_name, op1_node_name, x1, 0, 0)
# sub_fdfg1.add_edge(sub_fdfg1.source_node_name, op1_node_name, y1, 1, 1)
# sub_fdfg1.add_edge(op1_node_name, sub_fdfg1.sink_node_name, z1, 0, 0)

# # Sub FDFG 2
# sub_fdfg2.add_node(op2_node_name, op2_node)
# sub_fdfg2.add_edge(sub_fdfg2.source_node_name, op2_node_name, x2, 0, 0)
# sub_fdfg2.add_edge(sub_fdfg2.source_node_name, op2_node_name, y2, 1, 1)
# sub_fdfg2.add_edge(op2_node_name, sub_fdfg2.sink_node_name, z2, 0, 0)

# # Sub FDFG 3
# sub_fdfg3.add_node(op3_node_name, op3_node)
# sub_fdfg3.add_edge(sub_fdfg3.source_node_name, op3_node_name, x3, 0, 0)
# sub_fdfg3.add_edge(sub_fdfg3.source_node_name, op3_node_name, y3, 1, 1)
# sub_fdfg3.add_edge(op3_node_name, sub_fdfg3.sink_node_name, z3, 0, 0)

# # Sub FDFG 4
# sub_fdfg4.add_node(op4_node_name, op4_node)
# sub_fdfg4.add_edge(sub_fdfg4.source_node_name, op4_node_name, x4, 0, 0)
# sub_fdfg4.add_edge(sub_fdfg4.source_node_name, op4_node_name, y4, 1, 1)
# sub_fdfg4.add_edge(op4_node_name, sub_fdfg4.sink_node_name, z4, 0, 0)

# # Define FunctionNodes for sub-FDFGs
# function1_node_name = Identifier("function1_node")
# function1_node = FunctionNode(Identifier("function1"), fdfg=sub_fdfg1)

# function2_node_name = Identifier("function2_node")
# function2_node = FunctionNode(Identifier("function2"), fdfg=sub_fdfg2)

# function3_node_name = Identifier("function3_node")
# function3_node = FunctionNode(Identifier("function3"), fdfg=sub_fdfg3)

# function4_node_name = Identifier("function4_node")
# function4_node = FunctionNode(Identifier("function4"), fdfg=sub_fdfg4)

# # Create deeply nested sub-FDFGs within sub-FDFGs
# nested_sub_fdfg = FDFG()
# nested_x = Identifier("nested_x")
# nested_y = Identifier("nested_y")
# nested_z = Identifier("nested_z")
# nested_op_node_name = Identifier("nested_op")
# nested_op_node = PrimitiveNode(fdfg_op.add_op)

# nested_sub_fdfg.add_node(nested_op_node_name, nested_op_node)
# nested_sub_fdfg.add_edge(nested_sub_fdfg.source_node_name, nested_op_node_name, nested_x, 0, 0)
# nested_sub_fdfg.add_edge(nested_sub_fdfg.source_node_name, nested_op_node_name, nested_y, 1, 1)
# nested_sub_fdfg.add_edge(nested_op_node_name, nested_sub_fdfg.sink_node_name, nested_z, 0, 0)

# nested_function_node_name = Identifier("nested_function_node")
# nested_function_node = FunctionNode(Identifier("nested_function"), fdfg=nested_sub_fdfg)

# # Add nested function node to sub-FDFG 1
# sub_fdfg1.add_node(nested_function_node_name, nested_function_node)
# sub_fdfg1.add_edge(sub_fdfg1.source_node_name, nested_function_node_name, x1, 2, 2)
# sub_fdfg1.add_edge(nested_function_node_name, sub_fdfg1.sink_node_name, y1, 3, 3)

# # Add nodes and edges to main FDFG
# main_fdfg.add_node(function1_node_name, function1_node)
# main_fdfg.add_node(function2_node_name, function2_node)
# main_fdfg.add_node(function3_node_name, function3_node)
# main_fdfg.add_node(function4_node_name, function4_node)

# # Add more connections to make it dense
# main_fdfg.add_edge(main_fdfg.source_node_name, function1_node_name, a, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, function1_node_name, b, 1, 1)
# main_fdfg.add_edge(function1_node_name, function2_node_name, c, 0, 0)
# main_fdfg.add_edge(function1_node_name, function3_node_name, d, 1, 1)
# main_fdfg.add_edge(function1_node_name, function4_node_name, e, 2, 2)
# main_fdfg.add_edge(function2_node_name, function3_node_name, f, 0, 0)
# main_fdfg.add_edge(function2_node_name, function4_node_name, g, 1, 1)
# main_fdfg.add_edge(function3_node_name, function4_node_name, h, 2, 2)
# main_fdfg.add_edge(function4_node_name, main_fdfg.sink_node_name, i, 0, 0)
# main_fdfg.add_edge(function3_node_name, main_fdfg.sink_node_name, j, 1, 1)
# main_fdfg.add_edge(function2_node_name, main_fdfg.sink_node_name, k, 2, 2)
# main_fdfg.add_edge(function1_node_name, main_fdfg.sink_node_name, l, 3, 3)

# # Add loops and more connections to increase density
# loop_fdfg = FDFG()
# _x = Identifier("_x")
# _y = Identifier("_y")
# _z = Identifier("_z")
# loop_op_node_name = Identifier("loop_op")
# loop_op_node = PrimitiveNode(fdfg_op.add_op)

# loop_fdfg.add_node(loop_op_node_name, loop_op_node)
# loop_fdfg.add_edge(loop_fdfg.source_node_name, loop_op_node_name, _x, 0, 0)
# loop_fdfg.add_edge(loop_fdfg.source_node_name, loop_op_node_name, _y, 1, 1)
# loop_fdfg.add_edge(loop_op_node_name, loop_fdfg.sink_node_name, _z, 0, 0)

# loop_node_name = Identifier("loop")
# loop_node = LoopNode({i}, fdfg=loop_fdfg)

# main_fdfg.add_node(loop_node_name, loop_node)
# main_fdfg.add_edge(main_fdfg.source_node_name, loop_node_name, a, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, loop_node_name, b, 1, 1)
# main_fdfg.add_edge(loop_node_name, function1_node_name, c, 0, 0)
# main_fdfg.add_edge(loop_node_name, function2_node_name, d, 1, 1)
# main_fdfg.add_edge(loop_node_name, function3_node_name, e, 2, 2)
# main_fdfg.add_edge(loop_node_name, function4_node_name, f, 3, 3)

# # Add nested loops
# nested_loop_fdfg = FDFG()
# _nested_x = Identifier("_nested_x")
# _nested_y = Identifier("_nested_y")
# _nested_z = Identifier("_nested_z")
# nested_loop_op_node_name = Identifier("nested_loop_op")
# nested_loop_op_node = PrimitiveNode(fdfg_op.mul_op)

# nested_loop_fdfg.add_node(nested_loop_op_node_name, nested_loop_op_node)
# nested_loop_fdfg.add_edge(nested_loop_fdfg.source_node_name, nested_loop_op_node_name, _nested_x, 0, 0)
# nested_loop_fdfg.add_edge(nested_loop_fdfg.source_node_name, nested_loop_op_node_name, _nested_y, 1, 1)
# nested_loop_fdfg.add_edge(nested_loop_op_node_name, nested_loop_fdfg.sink_node_name, _nested_z, 0, 0)

# nested_loop_node_name = Identifier("nested_loop")
# nested_loop_node = LoopNode({j}, fdfg=nested_loop_fdfg)

# main_fdfg.add_node(nested_loop_node_name, nested_loop_node)
# main_fdfg.add_edge(main_fdfg.source_node_name, nested_loop_node_name, g, 0, 0)
# main_fdfg.add_edge(main_fdfg.source_node_name, nested_loop_node_name, h, 1, 1)
# main_fdfg.add_edge(nested_loop_node_name, loop_node_name, i, 0, 0)
# main_fdfg.add_edge(nested_loop_node_name, function1_node_name, j, 1, 1)
# main_fdfg.add_edge(nested_loop_node_name, function2_node_name, k, 2, 2)
# main_fdfg.add_edge(nested_loop_node_name, function3_node_name, l, 3, 3)

# # Add another level of nested sub-graphs
# deep_nested_sub_fdfg = FDFG()
# deep_nested_x = Identifier("deep_nested_x")
# deep_nested_y = Identifier("deep_nested_y")
# deep_nested_z = Identifier("deep_nested_z")
# deep_nested_op_node_name = Identifier("deep_nested_op")
# deep_nested_op_node = PrimitiveNode(fdfg_op.sub_op)

# deep_nested_sub_fdfg.add_node(deep_nested_op_node_name, deep_nested_op_node)
# deep_nested_sub_fdfg.add_edge(deep_nested_sub_fdfg.source_node_name, deep_nested_op_node_name, deep_nested_x, 0, 0)
# deep_nested_sub_fdfg.add_edge(deep_nested_sub_fdfg.source_node_name, deep_nested_op_node_name, deep_nested_y, 1, 1)
# deep_nested_sub_fdfg.add_edge(deep_nested_op_node_name, deep_nested_sub_fdfg.sink_node_name, deep_nested_z, 0, 0)

# deep_nested_function_node_name = Identifier("deep_nested_function_node")
# deep_nested_function_node = FunctionNode(Identifier("deep_nested_function"), fdfg=deep_nested_sub_fdfg)

# # Add deep nested function node to nested loop
# nested_loop_fdfg.add_node(deep_nested_function_node_name, deep_nested_function_node)
# nested_loop_fdfg.add_edge(nested_loop_fdfg.source_node_name, deep_nested_function_node_name, _nested_x, 2, 2)
# nested_loop_fdfg.add_edge(deep_nested_function_node_name, nested_loop_fdfg.sink_node_name, _nested_y, 3, 3)

# fdfg = main_fdfg


# Convert NetworkX graph to Dash Cytoscape elements
elements = nx_to_cytoscape(fdfg.graph)

# Set app layout
app.layout = create_dash_layout(elements)

if __name__ == "__main__":
    app.run_server(debug=True)