[tox]
envlist = lint, type, coverage, docs, py{311}

[testenv]
description = Run Unit Tests
extras = test
commands = 
    python --version
    pytest {posargs}

[testenv:coverage]
description = Analyze Pytest Code Coverage
usedevelop = true  # Required to register subprocess coverage of cli
extras = test
commands =
    python --version
    pytest --cov=fhy --cov-report term-missing --cov-fail-under=90 {posargs} 

[testenv:lint]
description = Run Code Linters
extras = lint
commands = 
    python --version
    ruff check --config pyproject.toml {posargs: fhy}
    ruff format --check --config pyproject.toml {posargs: fhy}
    pylint --rcfile pyproject.toml {posargs: fhy}

[testenv:type]
description = Static Type Analysis
extras = type
commands = 
    python --version
    mypy --config-file pyproject.toml {posargs: fhy}

[testenv:docs]
description = Confirm doc build
extras = docs
commands = 
    python --version
    sphinx-build -n -T -W -b html -d {envtmpdir}/_build/doctrees docs/source {envtmpdir}/_build/html