[tox]
envlist = lint, type, py{38,39,310,311}

[testenv]
description = Run Unit Tests
extras = test
commands = 
    python --version
    pytest {posargs}

[testenv:lint]
description = Run Code Linters
extras = lint
commands = 
    python --version
    ruff check {posargs: fhy}

[testenv:type]
description = Run Static Type Checks
extras = type
commands = 
    python --version
    mypy --config-file pyproject.toml {posargs: fhy}