[tox]
envlist = lint, type, py{311}

[testenv]
description = Run Unit Tests and Code Coverage
usedevelop = true  # Required to register subprocess coverage of cli
extras = test
commands = 
    python --version
    pytest {posargs}

[testenv:lint]
description = Run Code Linters
extras = lint
commands = 
    python --version
    ruff check --config pyproject.toml {posargs: fhy}
    ruff format --check --config pyproject.toml {posargs: fhy}

[testenv:type]
description = Run Static Type Checks
extras = type
commands = 
    python --version
    mypy --config-file pyproject.toml {posargs: fhy}